apiVersion: apps/v1
kind: Deployment
metadata:
  name: area-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: area-service
  template:
    metadata:
      labels:
        app: area-service
    spec:
      containers:
        - name: area-service
          image: area-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3010
---
apiVersion: v1
kind: Service
metadata:
  name: area-service
spec:
  type: NodePort
  selector:
    app: area-service
  ports:
    - protocol: TCP
      port: 3010
      targetPort: 3010
