apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: ticket-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3020
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  type: NodePort
  selector:
    app: ticket-service
  ports:
    - protocol: TCP
      port: 3020
      targetPort: 3020
